Add pg_stat_wal, pg_stat_replication_slots, and new pg_stat_database fields
1and1/pg-exporter pull request #6
Opened 2022-03-14 16:05 UTC by df7cb

Close #4.

2022-03-21 10:36 UTC, tbe requested changes
See inline comments. Also, for version dependent fields, the SQL Query must be written by hand. So for example https://github.com/1and1/pg-exporter/blob/3c62cc78463883b712d1e67db222d1e6f75757ee/collector/activity.go#L88

Else, we will get SQL Errors, as the ORM queries all columns per default.

2022-03-21 10:36 UTC, tbe commented on collector/models/pgStatDatabase.go
> +	sessionTime  Milliseconds `pg:"session_time" help:"Time spent by database sessions in this database, in milliseconds" metric:"session_time_total"` // new in PG14
Fields must be exported (upercase), so the database library can see and populate them.

2022-03-21 10:36 UTC, tbe commented on collector/models/pgStatDatabase.go
> +	checksumFailures int64    `pg:"checksum_failures" help:"Number of data page checksum failures detected in this database" metric:"checksum_failures_count"` // new in PG12
New fields, that are not present in all database versions must be nullable. Please use `sql.NullInt64`, `NullMilliseconds`, ...

2022-06-09 08:51 UTC, tbe approved these changes

2022-06-09 08:57 UTC, merged

2022-06-09 08:57 UTC, tbe commented
Looks good, merged to master

2022-06-09 11:47 UTC, df7cb commented
Thanks, but I wasn't finished yet :D. Expect a few more changes to come.